export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED';
export const EMAIL_IS_FREE = "EMAIL_IS_FREE";